const POSITION = {
  WORSHIPLEADER: 'WORSHIPLEADER',
  SINGER: 'SINGER',
  KEYBOARD: 'KEYBOARD',
  BASS: 'BASS',
  DRUM: 'DRUM',
  MULTIMEDIA: 'MULTIMEDIA',
  CAMERA: 'CAMERA'
};

const GENDER = {
  PRIA: 'PRIA',
  WANITA: 'WANITA'
}

const STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  OFF: 'OFF'
}

const POPULATION_NUMBER = 10;

module.exports = {
  POSITION,
  GENDER,
  STATUS,
  POPULATION_NUMBER
}